/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.sellaway.cart.objects;
@org.apache.avro.specific.AvroGenerated
public enum AddressType implements org.apache.avro.generic.GenericEnumSymbol<AddressType> {
  shipping, billing, shippingbilling  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"AddressType\",\"namespace\":\"io.sellaway.cart.objects\",\"symbols\":[\"shipping\",\"billing\",\"shippingbilling\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
