/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.sellaway.cart.objects;
@org.apache.avro.specific.AvroGenerated
public enum CartStatusType implements org.apache.avro.generic.GenericEnumSymbol<CartStatusType> {
  placed, in_progress, abandoned  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"CartStatusType\",\"namespace\":\"io.sellaway.cart.objects\",\"symbols\":[\"placed\",\"in_progress\",\"abandoned\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
