/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.sellaway.cart.objects;
@org.apache.avro.specific.AvroGenerated
public enum PaymentType implements org.apache.avro.generic.GenericEnumSymbol<PaymentType> {
  Visa, MasterCard, Discover, Amex, Giftcard  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"PaymentType\",\"namespace\":\"io.sellaway.cart.objects\",\"symbols\":[\"Visa\",\"MasterCard\",\"Discover\",\"Amex\",\"Giftcard\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
