/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.sellaway.cart.objects;
@org.apache.avro.specific.AvroGenerated
public enum ShippingMethodType implements org.apache.avro.generic.GenericEnumSymbol<ShippingMethodType> {
  bopis, standard, twoday, nextday  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ShippingMethodType\",\"namespace\":\"io.sellaway.cart.objects\",\"symbols\":[\"bopis\",\"standard\",\"twoday\",\"nextday\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
