/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.sellaway.cart.objects;
@org.apache.avro.specific.AvroGenerated
public enum WalletType implements org.apache.avro.generic.GenericEnumSymbol<WalletType> {
  ApplePay, Paypal  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"WalletType\",\"namespace\":\"io.sellaway.cart.objects\",\"symbols\":[\"ApplePay\",\"Paypal\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
